es: {
  "nav-home": "Inicio",
  "nav-portfolio": "Portfolio ▾",
  "nav-games": "🎮 Juegos",
  "nav-projects": "💡 Proyectos",
  "nav-contact": "Contacto",
  "nav-donate": "Donar",
  "nav-about": "Sobre mí",
  "home-title": "Bienvenido a mi web",
  "home-desc": "Explora mis proyectos y juegos. Aquí podrás conocer mi trabajo y contactarme si quieres colaborar.",
  "games-title": "🎮 Juegos",
  "games-text": "Actualmente no hay juegos publicados, ¡pero pronto añadiré mis creaciones!",
  "projects-title": "💡 Proyectos",
  "contact-title": "Contacto",
  "contact-desc": "Para cualquier consulta o colaboración, puedes escribirme al correo: swelen47@gmail.com",
  "donate-title": "Apoya mi trabajo",
  "donate-desc": "¡Gracias por visitar mi portfolio! 🙌 Todo mi contenido lo hago con dedicación y pasión. Si quieres apoyarme, cualquier donación será muy apreciada.",
  "donate-button": "☕ Invítame a un café en Ko-fi",
  "about-title": "Sobre Sw3l3n",
  "about-desc": "¡Hola! Soy <b>Sw3l3n</b>, apasionado del desarrollo web y creación de videojuegos. Desde pequeño me ha fascinado la tecnología y la creatividad digital, así que decidí combinar ambas para crear proyectos únicos y divertidos.",
  "about-desc2": "Gracias por visitar mi portfolio, espero que disfrutes explorando mi trabajo. ¡No dudes en contactarme si quieres colaborar o simplemente decir hola!"
},
en: {
  "nav-home": "Home",
  "nav-portfolio": "Portfolio ▾",
  "nav-games": "🎮 Games",
  "nav-projects": "💡 Projects",
  "nav-contact": "Contact",
  "nav-donate": "Donate",
  "nav-about": "About Me",
  "home-title": "Welcome to my website",
  "home-desc": "Explore my projects and games. Here you can see my work and contact me if you want to collaborate.",
  "games-title": "🎮 Games",
  "games-text": "I don't have any games published yet, but I will add them soon!",
  "projects-title": "💡 Projects",
  "contact-title": "Contact",
  "contact-desc": "For any question or collaboration, you can email me at: swelen47@gmail.com
